In [1]:
import torch
import torchvision

In [4]:
print(torch.__version__)
print(torchvision.__version__)
print('CUDA: ', torch.cuda.is_available())
a = torch.cuda.FloatTensor(2).zero_()
print(a)
b = torch.randn(2).cuda()
print(b)
c = a + b
print(c)

1.6.0
0.7.0a0+78ed10c
CUDA:  True
tensor([0., 0.], device='cuda:0')
tensor([-0.3655,  0.2321], device='cuda:0')
tensor([-0.3655,  0.2321], device='cuda:0')
